name: Tests

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**/*.php'
      - 'tests/**/*.php'
      - 'composer.json'
      - 'phpunit.dist.xml'
      - '.github/workflows/tests.yml'
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: ["8.3", "8.4", "8.5"]
        laravel: ["^12.0", "^13.0"]
        dependencies:
          - "highest"
          - "lowest"

    name: Run tests - PHP ${{ matrix.php }}/Laravel ${{ matrix.laravel }} ${{ matrix.dependencies == 'highest' && '⬆️' || '⬇️' }}

    steps:
      - uses: actions/checkout@v6
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: xdebug

      - name: Install dependencies
        uses: ramsey/composer-install@v4
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--no-cache --with=illuminate/support:${{ matrix.laravel }}"

      - name: Run tests
        run: vendor/bin/pest --ci
